---
- name: Start CS2 Server
  hosts: cs2
  become: true
  become_user: cs2server

  tasks:
    - name: Vérifier si le serveur tourne déjà
      shell: pgrep -f "cs2 -dedicated"
      register: cs2_process
      failed_when: false
      changed_when: false

    - name: Démarrer le serveur CS2
      shell: screen -S cs2 -d -m /home/cs2server/start_cs2.sh
      args:
        chdir: /home/cs2server
      when: cs2_process.rc != 0

    - name: Serveur déjà en cours d'exécution
      debug:
        msg: "Le serveur CS2 tourne déjà."
      when: cs2_process.rc == 0
