---
- name: CS2 Server Status
  hosts: cs2
  become: true
  become_user: cs2server

  tasks:
    - name: Vérifier le processus CS2
      shell: pgrep -af "cs2 -dedicated"
      register: cs2_process
      failed_when: false
      changed_when: false

    - name: Afficher le statut
      debug:
        msg: >-
          {{ 'RUNNING — PID: ' + cs2_process.stdout.split()[0] if cs2_process.rc == 0 else 'STOPPED' }}
