---
- name: Stop CS2 Server
  hosts: cs2
  become: true
  become_user: cs2server

  tasks:
    - name: Vérifier si le serveur tourne
      shell: pgrep -f "cs2 -dedicated"
      register: cs2_process
      failed_when: false
      changed_when: false

    - name: Arrêter le serveur CS2
      shell: screen -S cs2 -X stuff "quit$(printf '\r')"
      when: cs2_process.rc == 0

    - name: Attendre l'arrêt
      pause:
        seconds: 5
      when: cs2_process.rc == 0

    - name: Serveur déjà arrêté
      debug:
        msg: "Le serveur CS2 n'est pas en cours d'exécution."
      when: cs2_process.rc != 0
